In [1]:

# This model is a Logistic Regression 
#as we want to predict whether or not an individual has a mental health disorder (output: yes or no).

In [2]:

# Import dependencies
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
import numpy as np

In [3]:
# Load data
csv = pd.read_csv('Data_Clean_2017_to_2019.csv')
data = pd.DataFrame(csv)
data.head(50)

,Unnamed: 0,age,"Gender: F=0, M=1, Non-binary=3","If possibly, what disorder(s) do you believe you have?",Have you ever been diagnosed with a mental health disorder? Y=1 N=0,Have you had a mental health disorder in the past? Y=1 N=0,Do you have a family history of mental illness? Y=1 N=0,Are you self-employed? Y=1 N=0,Is your employer primarily a tech company/organization? Y=1 N=0,How many employees does your company or organization have?,Age Groups,Employee_Range
0,0,25.0,1,NaN,0,0,0,0,0,26-100,24-30,3
1,1,51.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,1,0,0,26-100,46-55,3
2,2,27.0,1,NaN,0,0,0,0,0,26-100,24-30,3
3,3,37.0,1,NaN,0,0,1,0,0,100-500,31-45,4
4,4,46.0,1,NaN,0,0,0,0,0,26-100,46-55,3
5,5,36.0,0,NaN,1,1,1,0,0,100-500,31-45,4
6,6,39.0,0,NaN,1,1,1,0,0,26-100,31-45,3
7,7,35.0,1,"Substance Use Disorder, Mood Disorder (Depress...",0,0,1,1,0,NaN,31-45,999
8,8,49.0,2,NaN,0,0,0,0,0,26-100,46-55,3
9,9,45.0,1,"Mood Disorder (Depression, Bipolar Disorder, e...",0,0,0,0,0,05-25,31-45,999
10,10,40.0,1,NaN,0,0,0,0,0,100-500,31-45,4
11,11,37.0,1,NaN,0,0,0,1,0,NaN,31-45,999
12,12,31.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,1,0,0,more than 1000,31-45,999
13,13,37.0,1,NaN,1,1,1,0,0,500-1000,31-45,5
14,14,26.0,0,NaN,1,1,0,0,0,100-500,24-30,4
15,15,43.0,1,NaN,1,1,0,0,0,100-500,31-45,4
16,16,35.0,1,"Mood Disorder (Depression, Bipolar Disorder, e...",0,0,1,0,0,100-500,31-45,4
17,17,31.0,1,NaN,0,0,1,1,0,NaN,31-45,999
18,18,32.0,0,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,1,0,0,100-500,31-45,4
19,19,37.0,1,NaN,1,1,0,0,0,more than 1000,31-45,999
20,20,41.0,1,NaN,0,0,0,0,0,05-25,31-45,999
21,21,40.0,0,NaN,1,1,1,0,0,100-500,31-45,4
22,22,37.0,1,NaN,1,1,0,0,0,500-1000,31-45,5
23,23,53.0,1,"Mood Disorder (Depression, Bipolar Disorder, e...",0,0,1,0,0,100-500,46-55,4
24,24,29.0,1,NaN,0,0,1,0,0,05-25,24-30,999
25,25,37.0,1,NaN,1,1,1,0,0,500-1000,31-45,5
26,26,45.0,0,NaN,1,1,1,0,0,100-500,31-45,4
27,27,26.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,0,0,0,05-25,24-30,999
28,28,28.0,1,NaN,1,1,1,0,0,100-500,24-30,4
29,29,24.0,0,NaN,1,1,0,0,0,100-500,24-30,4
30,30,27.0,1,"Mood Disorder (Depression, Bipolar Disorder, e...",0,0,1,0,0,100-500,24-30,4
31,31,42.0,1,NaN,0,0,0,0,0,100-500,31-45,4
32,32,53.0,0,NaN,0,0,0,1,0,NaN,46-55,999
33,33,34.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,0,0,0,100-500,31-45,4
34,34,23.0,2,NaN,1,1,0,0,0,500-1000,16-23,5
35,35,34.0,1,NaN,0,0,0,0,0,more than 1000,31-45,999
36,36,27.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,1,0,0,05-25,24-30,999
37,37,31.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,0,0,0,100-500,31-45,4
38,38,30.0,1,NaN,0,0,0,1,0,NaN,24-30,999
39,39,58.0,1,NaN,1,1,0,1,0,NaN,56+,999
40,40,50.0,1,NaN,0,0,0,0,0,more than 1000,46-55,999
41,41,41.0,1,NaN,1,1,1,0,0,100-500,31-45,4
42,42,40.0,1,"Stress Response Syndromes, Mood Disorder (Depr...",0,0,0,0,0,26-100,31-45,3
43,43,28.0,1,NaN,1,1,0,1,0,NaN,24-30,999
44,44,49.0,1,NaN,0,0,0,0,0,01-5,46-55,999
45,45,37.0,1,NaN,1,1,1,0,0,more than 1000,31-45,999
46,46,36.0,1,NaN,1,1,0,1,0,NaN,31-45,999
47,47,52.0,1,"Attention Deficit Hyperactivity Disorder, Anxi...",0,0,0,0,0,05-25,46-55,999
48,48,33.0,2,NaN,0,0,0,0,0,more than 1000,31-45,999
49,49,54.0,0,NaN,0,0,0,1,0,NaN,46-55,999

In [4]:
# Rename ind and dep variable columns
renamed_data = data.rename(columns = {'Gender: F=0, M=1, Non-binary=3':'gender',\
                                      'Have you ever been diagnosed with a mental health disorder? Y=1 N=0':'mentalHealthDisorder',\
                                      'Are you self-employed?  Y=1 N=0':'selfEmployment',\
                                     'Do you have a family history of mental illness?  Y=1 N=0':'familyHist',\
                                     'age':'Age',\
                                     'Is your employer primarily a tech company/organization?  Y=1 N=0':'techComp'
                                      
                                    
                                     })
renamed_data

,Unnamed: 0,Age,gender,"If possibly, what disorder(s) do you believe you have?",mentalHealthDisorder,Have you had a mental health disorder in the past? Y=1 N=0,familyHist,selfEmployment,techComp,How many employees does your company or organization have?,Age Groups,Employee_Range
0,0,25.0,1,NaN,0,0,0,0,0,26-100,24-30,3
1,1,51.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,1,0,0,26-100,46-55,3
2,2,27.0,1,NaN,0,0,0,0,0,26-100,24-30,3
3,3,37.0,1,NaN,0,0,1,0,0,100-500,31-45,4
4,4,46.0,1,NaN,0,0,0,0,0,26-100,46-55,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1520,751,41.0,1,NaN,0,0,0,0,0,26-100,31-45,3
1521,752,40.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",1,1,0,0,0,05-25,31-45,999
1522,753,NaN,2,"Anxiety Disorder (Generalized, Social, Phobia,...",1,1,1,1,0,NaN,NaN,999
1523,754,30.0,1,"Anxiety Disorder (Generalized, Social, Phobia,...",0,0,0,0,0,26-100,24-30,3
1524,755,NaN,2,"Anxiety Disorder (Generalized, Social, Phobia,...",1,1,1,1,0,NaN,NaN,999

In [5]:
# # Convert col to strings
# renamed_data.formalDiscussion = renamed_data.formalDiscussion.astype(str)

In [56]:
#taking gender as the independent variable
# # Clean to only 'Yes' or 'No'
# new_col = []

# # Loop through dataframe
# for data in renamed_data.values:
    
#     if (str(data[6]).lower() != 'yes') and (str(data[6]).lower() != 'no'):
#         data[6] = None
#     new_col.append(data[6])

# # Create new df
# renamed_data.formalDiscussion = new_col

        
df = renamed_data.dropna(subset=['Employee_Range'])
renamed_data.head(10)

,Unnamed: 0,Age,gender,"If possibly, what disorder(s) do you believe you have?",mentalHealthDisorder,Have you had a mental health disorder in the past? Y=1 N=0,familyHist,selfEmployment,techComp,How many employees does your company or organization have?,Age Groups,Employee_Range
0,0,25.0,1,NaN,0,0,0,0,0,26-100,24-30,3
1,1,51.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,1,0,0,26-100,46-55,3
2,2,27.0,1,NaN,0,0,0,0,0,26-100,24-30,3
3,3,37.0,1,NaN,0,0,1,0,0,100-500,31-45,4
4,4,46.0,1,NaN,0,0,0,0,0,26-100,46-55,3
5,5,36.0,0,NaN,1,1,1,0,0,100-500,31-45,4
6,6,39.0,0,NaN,1,1,1,0,0,26-100,31-45,3
7,7,35.0,1,"Substance Use Disorder, Mood Disorder (Depress...",0,0,1,1,0,NaN,31-45,999
8,8,49.0,2,NaN,0,0,0,0,0,26-100,46-55,3
9,9,45.0,1,"Mood Disorder (Depression, Bipolar Disorder, e...",0,0,0,0,0,05-25,31-45,999

In [57]:
#taking gender as the independent variable
# # Clean to only 'Yes' or 'No'
# new_col = []

# # Loop through dataframe
# for data in renamed_data.values:
    
#     if (str(data[6]).lower() != 'yes') and (str(data[6]).lower() != 'no'):
#         data[6] = None
#     new_col.append(data[6])

# # Create new df
# renamed_data.formalDiscussion = new_col

        
#df = renamed_data.dropna(subset=['familyHist'])
#renamed_data.head(10)

In [58]:
#taking age as the independent variable
# # Clean to only 'Yes' or 'No'
# new_col = []

# # Loop through dataframe
# for data in renamed_data.values:
    
#     if (str(data[6]).lower() != 'yes') and (str(data[6]).lower() != 'no'):
#         data[6] = None
#     new_col.append(data[6])

# # Create new df
# renamed_data.formalDiscussion = new_col

        
#df = renamed_data.dropna(subset=['Age'])
#renamed_data.head(10)

In [59]:
#taking gender as the independent variable
# # Clean to only 'Yes' or 'No'
# new_col = []

# # Loop through dataframe
# for data in renamed_data.values:
    
#     if (str(data[6]).lower() != 'yes') and (str(data[6]).lower() != 'no'):
#         data[6] = None
#     new_col.append(data[6])

# # Create new df
# renamed_data.formalDiscussion = new_col

        
#df = renamed_data.dropna(subset=['pastHist'])
#renamed_data.head(10)

In [60]:
## Potential independent variables:
# Age
# Gender
# Self Employment
# Remote Working Situation

## Dependent variable:
# Whether they have been diagnosed with a mental health disorder by a medical professional

In [62]:
# Potential independent variable = whether manager has had formal discussion about mental health importance and 
# opportunities with employee
X = df.Employee_Range.values.reshape(-1,1)

In [63]:
# Potential independent variable = whether manager has had formal discussion about mental health importance and 
# opportunities with employee
#X = df.age.values.reshape(-1,1)

In [64]:
# Potential independent variable = whether manager has had formal discussion about mental health importance and 
# opportunities with employee
#X = df.selfEmployment.values.reshape(-1,1)

In [65]:
# Potential independent variable = whether manager has had formal discussion about mental health importance and 
# opportunities with employee
#X = df.familyHist.values.reshape(-1,1)

In [66]:
# Potential independent variable = whether manager has had formal discussion about mental health importance and 
# opportunities with employee
#X = df.pastHist.values.reshape(-1,1)

In [67]:
# Dependent vairable = whether the employee has been diagnosed with a mental health disorder
y = df.mentalHealthDisorder.values.reshape(-1,1)

In [68]:
# Split data into training and testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

In [69]:
# Create logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)

In [70]:

## Train data
classifier.fit(X_train, y_train.ravel())

LogisticRegression(random_state=1)

In [71]:
## Predict outcomes for test data
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test.ravel()})

     Prediction  Actual
0             0       0
1             0       0
2             0       0
3             0       1
4             0       0
..          ...     ...
377           0       1
378           0       0
379           0       0
380           0       0
381           0       1

[382 rows x 2 columns]

In [72]:
# Validate model with test data
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.5759162303664922

In [22]:
# Cleaned Data ML Tests:

## Gender*
### Accuracy: 0.6020942408376964 - *Highest so far, but we can test other variables to find a stronger correlation.
### Greater accuracy than age but still not at desired output.

## Age
### Accuracy: 0.5774278215223098 
### Age doesn't see to have a strong correlation with mental health disorder (MHD) rates in the tech industry.

## Self-Employment
### Accuracy: 0.5759162303664922 
### Lowest accuracy - self-employment status does not seem to have a strong correlation with MHD rates in tech.

In [23]:
# Description of model, preliminary processing/selection, and data splitting in main README.md

In [24]:
# Step 2 - After selecting effective variable, test by generating new data point.

In [25]:
# ## Generate new data point 
# import numpy as np
# new_data = np.random.randint(2, size=1)

In [26]:
# # Prediction of the new data point
# predictions = classifier.predict(new_data)
# print("Classes are either 0 (no mental health disorder diagnosis) or 1 (mental health disorder diagnosis)")
# print(f"The new point was classified as: {predictions}")