In [32]:
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
import numpy as np

In [33]:
file = pd.read_csv('../../Deliverable2/HM/Data_Clean_2017_to_2019.csv')
df = pd.DataFrame(file)
df.head()

,Index,age,"Gender: F=0, M=1, Non-binary=3","If possibly, what disorder(s) do you believe you have?",Have you ever been diagnosed with a mental health disorder? Y=1 N=0,Have you had a mental health disorder in the past? Y=1 N=0,Do you have a family history of mental illness? Y=1 N=0,Are you self-employed? Y=1 N=0,Is your employer primarily a tech company/organization? Y=1 N=0,How many employees does your company or organization have?,Age Groups
0,0,25.0,1,NaN,0,0,0,0,0,26-100,24-30
1,1,51.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,1,0,0,26-100,46-55
2,2,27.0,1,NaN,0,0,0,0,0,26-100,24-30
3,3,37.0,1,NaN,0,0,1,0,0,100-500,31-45
4,4,46.0,1,NaN,0,0,0,0,0,26-100,46-55

In [34]:
df['age'].unique()

array([25., 51., 27., 37., 46., 36., 39., 35., 49., 45., 40., 31., 26.,
       43., 32., 41., 53., 29., 28., 24., 42., 34., 23., 30., 58., 50.,
       52., 33., 54., 38., 64., 55., 60., 47., 48., 20.,  0., 22., 63.,
       44., 59., 19., 56., 21., 57., 61., 67., 65., 18., 66., 62., nan])

In [35]:
df['age'].isna().count()

1525

In [37]:
df = df.fillna(0)
df.head()

,Index,age,"Gender: F=0, M=1, Non-binary=3","If possibly, what disorder(s) do you believe you have?",Have you ever been diagnosed with a mental health disorder? Y=1 N=0,Have you had a mental health disorder in the past? Y=1 N=0,Do you have a family history of mental illness? Y=1 N=0,Are you self-employed? Y=1 N=0,Is your employer primarily a tech company/organization? Y=1 N=0,How many employees does your company or organization have?,Age Groups
0,0,25.0,1,0,0,0,0,0,0,26-100,24-30
1,1,51.0,1,"Mood Disorder (Depression, Bipolar Disorder, etc)",0,0,1,0,0,26-100,46-55
2,2,27.0,1,0,0,0,0,0,0,26-100,24-30
3,3,37.0,1,0,0,0,1,0,0,100-500,31-45
4,4,46.0,1,0,0,0,0,0,0,26-100,46-55

In [42]:
df['age'].unique()

array([25., 51., 27., 37., 46., 36., 39., 35., 49., 45., 40., 31., 26.,
       43., 32., 41., 53., 29., 28., 24., 42., 34., 23., 30., 58., 50.,
       52., 33., 54., 38., 64., 55., 60., 47., 48., 20.,  0., 22., 63.,
       44., 59., 19., 56., 21., 57., 61., 67., 65., 18., 66., 62.])